# Generated by Django 4.1.1 on 2023-02-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_alter_cartitem_quantity_orderitem_billinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='product',
        ),
    ]
