# Generated by Django 4.1.1 on 2023-02-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
